### PR TITLE
Adding support for multiple accordions on the same page

### PR DESCRIPTION
**Pull request by noahmanger**
This updates the `Accordion` constructor so that it accepts an actual HTML element as its first argument, rather than relying on a generic selector to locate the elements. This makes it possible to have multiple accordions on the same page.

It also adds documentation for the constructor and renames the `body` property to `elm` for greater clarity.

Resolves https://github.com/18F/accordion/issues/10

### CODE REVIEW

**Comment by toolness** [comment]
Cool!  Have you considered adding a [changelog](http://keepachangelog.com/) that addresses the new API?  That way aside from a major version bump in npm, it will be easier for folks who are upgrading to understand what they need to do in order to upgrade, without needing to read through the diffs in the source code.

Also, I am new to this code, so I'm confused about this `example/main.js` file.  It seems to contain changes that are very similar (or identical to) those in `src/accordion.js`?  Is it meant to be a straight-up copy?

**Comment by toolness** [comment]
An alternative approach to requiring a passed-in DOM element as the first argument to the constructor might be to check to see if only two arguments were passed-in, and if so, default to the older behavior.  I'm not sure how many other users of this accordion exist and whether they'd appreciate the backwards-compatibility or not, but I thought I'd mention it just in case!

**Comment by toolness** [comment]
Hmm, I just noticed there seems to be a test suite at [`tests/accordion.js`](https://github.com/18F/accordion/blob/master/tests/accordion.js)... Don't some of those need to be updated to conform to the new API?  Seems like it'd also be useful to have a unit test or two in here to verify that your new functionality works!

**Comment by noahmanger** [comment]
Thanks @toolness . I'll add a changelog for sure, and will update tests (good call). The tough thing about the older behavior is that the two arguments were optional, so it's possible that they were left out entirely. 

This really should have been at v1.0.0 for a while now, but this seems like a good occasion to do so.

As for the example/main.js, this is just the compiled script to run the example. I know it's a little weird to check this in, but think it's nice if people can have an example that just works. What do you think?

**Comment by noahmanger** [comment]
Ok, added that stuff. Does that all make sense?

**Comment by toolness** [comment]
Nice, this looks great! 👍 

Regarding the changelog, the one thing I might be confused about if I were using the previous version might be "what should I set the first argument to, if I still just have one accordion on my page and want to upgrade as effortlessly as possible?"  If you don't expect there to be many folks who will be upgrading then it might not be a big deal though.

**Pull request merged**
